name: forecasting_tools

channels:
  - conda-forge

dependencies:
  - python=3.13
  - numpy
  - scipy
  - pandas<3
  - statsmodels
  - statsforecast>=2.1
  - matplotlib
  - plotly
  - jupyterlab
  - ipykernel
  - pytest
